var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,e,c){b instanceof String&&(b=String(b));for(var h=b.length,g=0;g<h;g++){var d=b[g];if(e.call(c,d,g,b))return{i:g,v:d}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,c){b!=Array.prototype&&b!=Object.prototype&&(b[e]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,e,c,h){if(e){c=$jscomp.global;b=b.split(".");for(h=0;h<b.length-1;h++){var g=b[h];g in c||(c[g]={});c=c[g]}b=b[b.length-1];h=c[b];e=e(h);e!=h&&null!=e&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
(function(){var b=[],e=0;window.generate_the_wcmp=function(c){function h(a,k){if(a+1<e||k){var f=a+1;!k||f!=e&&0!=d('[playernumber="'+f+'"]').closest("[data-loop]").length&&d('[playernumber="'+f+'"]').closest("[data-loop]")[0]==d('[playernumber="'+a+'"]').closest("[data-loop]")[0]||(f=d('[playernumber="'+a+'"]').closest("[data-loop]").find("[playernumber]:first").attr("playernumber"));b[f]instanceof d&&b[f].is("a")?b[f].is(":visible")?b[f].click():h(a+1,k):d(b[f].container).is(":visible")?b[f].play():
h(a+1,k)}}function g(a){var b=a.data("product");d('[data-product="'+b+'"]').each(function(){var a=d(this).closest(".product"),c=a.find("img.product-"+b);if(c.length&&0==a.closest(".wcmp-player-list").length&&0==a.find(".wcmp-player-list").length){var k=c.offset();a=a.find("div.wcmp-player");a.length&&a.css({position:"absolute","z-index":999999}).offset({left:k.left+(c.width()-a.width())/2,top:k.top+(c.height()-a.height())/2})}})}if(!("boolean"!==typeof c&&"undefined"!=typeof wcmp_global_settings&&
1*wcmp_global_settings.onload)&&"undefined"===typeof generated_the_wcmp){generated_the_wcmp=!0;var d=jQuery;d(".wcmp-player-container").on("click","*",function(a){a.preventDefault();a.stopPropagation();return!1}).parent().removeAttr("title");d.expr[":"].regex=function(a,b,c){b=c[3].split(",");var f=/^(data|css):/;c=b[0].match(f)?b[0].split(":")[0]:"attr";f=b.shift().replace(f,"");return(new RegExp(b.join("").replace(/^\s+|\s+$/g,""),"ig")).test(d(a)[c](f))};var q="undefined"!=typeof wcmp_global_settings?
wcmp_global_settings.play_all:!0,l="undefined"!=typeof wcmp_global_settings?!(1*wcmp_global_settings.play_simultaneously):!0,n="undefined"!=typeof wcmp_global_settings?1*wcmp_global_settings.fade_out:!0,p="undefined"!=typeof wcmp_global_settings&&"ios_controls"in wcmp_global_settings&&1*wcmp_global_settings.ios_controls?!0:!1;c=d("audio.wcmp-player:not(.track):not([playernumber])");var r=d("audio.wcmp-player.track:not([playernumber])"),m={pauseOtherPlayers:l,iPadUseNativeControls:p,iPhoneUseNativeControls:p,
success:function(a,c){var f=d(c).data("duration"),e=d(c).data("estimated_duration"),g=d(c).attr("playernumber");"undefined"!=typeof e&&(a.getDuration=function(){return e});"undefined"!=typeof f&&setTimeout(function(a,c){return function(){b[a].updateDuration=function(){d(this.media).closest(".wcmp-player").find(".mejs-duration").html(c)};b[a].updateDuration()}}(g,f),50);d(c).attr("volume")&&(a.setVolume(parseFloat(d(c).attr("volume"))),0==a.volume&&a.setMuted(!0));a.addEventListener("timeupdate",function(b){b=
a.getDuration();isNaN(a.currentTime)||isNaN(b)||(n&&4>b-a.currentTime?a.setVolume(a.volume-a.volume/3):a.currentTime&&("undefined"==typeof a.bkVolume&&(a.bkVolume=parseFloat(d(a).find("audio,video").attr("volume")||a.volume)),a.setVolume(a.bkVolume),0==a.bkVolume&&a.setMuted(!0)))});a.addEventListener("volumechange",function(b){b=a.getDuration();isNaN(a.currentTime)||isNaN(b)||!(4<b-a.currentTime)&&n||!a.currentTime||(a.bkVolume=a.volume)});a.addEventListener("ended",function(b){b=d(a).closest('[data-loop="1"]');
a.currentTime=0;if(1*q||b.length){var c=1*d(a).attr("playernumber");isNaN(c)&&(c=1*d(a).find("[playernumber]").attr("playernumber"));h(c,b.length)}})}};l=".product-type-grouped :regex(name,quantity\\[\\d+\\])";c.each(function(){var a=d(this);a.find("source").attr("src");a.attr("playernumber",e);m.audioVolume="vertical";try{b[e]=new MediaElementPlayer(a[0],m)}catch(k){"console"in window&&console.log(k)}e++});r.each(function(){var a=d(this);a.find("source").attr("src");a.attr("playernumber",e);m.features=
["playpause"];try{b[e]=new MediaElementPlayer(a[0],m)}catch(k){"console"in window&&console.log(k)}e++;g(a);d(window).resize(function(){g(a)})});d(l).length||(l=".product-type-grouped [data-product_id]");d(l).length||(l=".woocommerce-grouped-product-list [data-product_id]");d(l).length||(l='.woocommerce-grouped-product-list [id*="product-"]');d(l).each(function(){try{var a=d(this),b=(a.data("product_id")||a.attr("name")||a.attr("id")).replace(/[^\d]/g,""),c=d(".wcmp-player-list.merge_in_grouped_products .product-"+
b+":first .wcmp-player-title"),e=d("<table></table>");c.length&&!c.closest(".wcmp-first-in-product").length&&(c.closest("tr").addClass("wcmp-first-in-product"),0==c.closest("form").length&&c.closest(".wcmp-player-list").prependTo(a.closest("form")),e.append(a.closest("tr").prepend("<td>"+c.html()+"</td>")),c.html("").append(e))}catch(t){}})}};window.wcmp_force_init=function(){delete window.generated_the_wcmp;generate_the_wcmp(!0)};jQuery(generate_the_wcmp);jQuery(window).on("load",function(){generate_the_wcmp(!0);
var b=jQuery,e=window.navigator.userAgent;b("[data-lazyloading]").each(function(){var c=b(this);c.attr("preload",c.data("lazyloading"))});if(e.match(/iPad/i)||e.match(/iPhone/i))if("undefined"!=typeof wcmp_global_settings?wcmp_global_settings.play_all:1)b(".wcmp-player .mejs-play button").one("click",function(){if("undefined"==typeof wcmp_preprocessed_players){wcmp_preprocessed_players=!0;var c=b(this);b(".wcmp-player audio").each(function(){this.play();this.pause()});setTimeout(function(){c.click()},
500)}})}).on("popstate",function(){jQuery("audio[data-product]:not([playernumber])").length&&wcmp_force_init()});jQuery(document).on("scroll wpfAjaxSuccess woof_ajax_done yith-wcan-ajax-filtered wpf_ajax_success berocket_ajax_products_loaded berocket_ajax_products_infinite_loaded",wcmp_force_init)})();
